/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'first': string;
    /**
    * The last name
    */
    'last': string;
    /**
    * The middle name
    */
    'middle': string;
  }
  interface WcSidedrawer {
    'open': boolean;
    'titlename': string;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLWcSidedrawerElement extends Components.WcSidedrawer, HTMLStencilElement {}
  var HTMLWcSidedrawerElement: {
    prototype: HTMLWcSidedrawerElement;
    new (): HTMLWcSidedrawerElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'wc-sidedrawer': HTMLWcSidedrawerElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent extends JSXBase.HTMLAttributes<HTMLMyComponentElement> {
    /**
    * The first name
    */
    'first'?: string;
    /**
    * The last name
    */
    'last'?: string;
    /**
    * The middle name
    */
    'middle'?: string;
  }
  interface WcSidedrawer extends JSXBase.HTMLAttributes<HTMLWcSidedrawerElement> {
    'open'?: boolean;
    'titlename'?: string;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'wc-sidedrawer': WcSidedrawer;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


